resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- task: Bash@3
  displayName: 'Install dependencies'
  inputs:
    targetType: 'filePath'

    filePath: setup/setup.sh

- task: PythonScript@0
  displayName: 'Prep Environment for model creation'
  inputs:
    scriptPath: project/services/10_prepEnvModelCreation.py
    workingDirectory: project

- task: PythonScript@0
  displayName: 'Build model using Databricks'
  inputs:
    scriptPath: project/services/20_buildModelDatabricks.py
    workingDirectory: project

- task: PythonScript@0
  displayName: 'Create image from model'
  inputs:
    scriptPath: project/services/30_createImageFromModel.py
    workingDirectory: project

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'